### ISSUE TITLE
Specify babylon syntaxes to parse files?

### ISSUE THREAD

**Issue by infctr** [square/babel-codemod#147]
First of all thanks for the awesome codemod cli tool with ts support!

I'm terribly sorry if this was covered before, but I couldn't find an answer in examples and other issues. I've got a babel-plugin that I want to use to perform some changes on `.ts` and `.tsx` files. So my plugin already inherits `@babel/plugin-syntax-typescript` to make proper type checks as per [Babel Handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#-enabling-syntax-in-plugins) guidelines. How do I enable other Babylon syntaxes (jsx) to parse (not transform) files when running `babel-codemod`? Am I missing something here?

**Comment by infctr** [comment]
Figured it out, had to specify `babel-plugin-syntax-jsx` as the last plugin

```
./node_modules/.bin/codemod -p ./custom-codemod.js -p babel-plugin-syntax-jsx ./component.tsx
```

**Comment by eventualbuddha** [comment]
Can you show me your plugin, perhaps? Or enough to reproduce the problem?

**Comment by infctr** [comment]
Thanks for the feedback! This the [plugin](https://github.com/infctr/babel-plugin-codemod-named-export-declarations) I was testing, btw it also fails to parse jsx on your repo.

Error log
```
❯ ./node_modules/.bin/codemod -p babel-plugin-codemod-named-export-declarations react/HelloWorld.tsx
Encountered an error while processing react/HelloWorld.tsx:
SyntaxError: /Users/infctr/Projects/babel-codemod-examples/react/HelloWorld.tsx: Unexpected token, expected "," (11:21)

   9 | export default class HelloWorld extends React.Component<Props, {}> {
  10 |   render() {
> 11 |     return <div>{this.props.content}</div>
     |                      ^
  12 |   }
  13 | }
  14 |
    at _class.raise (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:3906:15)
    at _class.unexpected (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:5235:16)
    at _class.expect (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:5223:28)
    at _class.parseObj (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:6623:14)
    at _class.parseExprAtom (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:6281:21)
    at _class.parseExprSubscripts (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:5911:21)
    at _class.parseMaybeUnary (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:5890:21)
    at _class.parseMaybeUnary (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:10183:54)
    at _class.tsParseTypeAssertion (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:9267:30)
    at _class.parseMaybeUnary (/Users/infctr/Projects/babel-codemod-examples/node_modules/@babel/parser/lib/index.js:10181:21)
1 file(s), 0 modified, 1 errors
```

**Comment by eventualbuddha** [comment]
Interesting. Looks like removing the inheritance stuff makes it work:

```diff
diff --git a/src/index.js b/src/index.js
index 823892b..c00bbc9 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,7 +1,5 @@
 require('better-log/install');

-const babelPluginSyntaxTypescript = require('@babel/plugin-syntax-typescript');
-
 module.exports = babel => {
   const { types: t } = babel;

@@ -70,7 +68,6 @@ module.exports = babel => {
         node.id.name === name;

   return {
-    inherits: babelPluginSyntaxTypescript.default,
     visitor: {
       ExportNamedDeclaration: path => {
         const program = path.findParent(p => p.isProgram());
```

**Comment by infctr** [comment]
And it supports typescript out of the box too 😃

**Comment by eventualbuddha** [comment]
Yep 😊 If you encounter any other issues or have suggestions please let me know!
